name: geopulse
description: GeoPulse — hourly geopolitics front page for Android and iOS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  # firebase_core: ^3.1.0          # Uncomment after: flutterfire configure
  # firebase_messaging: ^15.0.0    # Uncomment after: flutterfire configure

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
